// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivxhtzssoaldnajkrkmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2eGh0enNzb2FsZG5hamtya21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTYzMTQsImV4cCI6MjA3Mjc5MjMxNH0.nGag63wOHLOwZLo8QJ6qi1Y_CW_BChdevLYZC1hllAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});